version: '3.8'
services:
  api:
    build: .
    ports:
      - '8000:8000'
    links:
      - db
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017
    image: princoo/demo-app

  db:
    image: 'mongo:latest'
    container_name: db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: loggs
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: secret

